version: "3"

services:
  times-database:
    image: timescale/timescaledb:latest-pg13
    container_name: transfers
    restart: always
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ../pg_data/times-database:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: times
      PGDATA: /var/lib/postgres/data/times-database/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1m
      timeout: 5s
      start_period: 10s
      retries: 3
  time-tracker-bot:
    container_name: time-tracker-bot
    build:
      dockerfile: Dockerfile
      context: .
    command: "/app/time-tracker-bot"
    environment:
      TELOXIDE: 5537831748:AAFsUw1--vcaIgAAB5CJNsEobTgNO6gi5Jc
      DATABASE_URL: postgres://postgres:admin@times-database:5432/times
